spring.application.name=recuerdame

# Database Configuration
spring.output.ansi.enabled=ALWAYS
spring.config.import=optional:file:.env[.properties]
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# Jpa/Hibernate Configuration
spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Logging Configuration
logging.level.org.springframework.security=DEBUG
logging.level.io.jsonwebtoken=DEBUG
logging.level.com.fcmh.femcodersmentorhub=DEBUG

# Server Configuration
server.port=${SERVER_PORT}